package org.example.rules;

import org.example.facts.data.LongFact
import org.example.facts.notification.Notification
import java.math.BigDecimal
import java.time.LocalDateTime


query getLongs()
    val: LongFact()
end

declare Notification
    @role( event )
    @expires( 1m )
end

declare Now
   time: long
end

rule "Init Now"
when
  not(Now())
then
 Now now = new Now();
 now.setTime(drools.getKieRuntime().getSessionClock().getCurrentTime());
 insert(now);
end

rule "Update Now"
  timer ( int: 0 1m )
when
  $now: Now()
then
  $now.setTime(drools.getKieRuntime().getSessionClock().getCurrentTime());
  update($now)
end